- hosts: localhost
  gather_facts: false
  vars_files:
    - /var/www/cgi-bin/ansible_codes/keywords.py
  tasks:
   - ec2:
      aws_access_key: ""
      aws_secret_key: "" 
      key_name: ""
      instance_type: "t2.micro"
      image: "-ami-5b673c34"
      region: "ap-south-1"
     # wait: yes 
     # vpc_subnet_id: ""
     # assign_public_ip: yes
