- hosts: "{{ ip }}"
  vars_files:
    - /var/www/cgi-bin/ansible_codes/keywords.py
  tasks:
     - name: collecting RAM data
       copy: 
          content: " {{ ansible_hostname }} has {{ ansible_memfree_mb }}MB free RAM"
          dest: "/var/www/html/index.html"
#          content: " {{ ansible_hostname }} has total RAM {{ ansible_memory_mb }}"
#          dest:  "/root/Desktop/show_ram.yml"
